name: "Install toolchains"
description: "Install toolchains"
runs:
  using: "composite"
  steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-02-03
        override: true
        target: wasm32-unknown-unknown
        components: rustfmt
    - run: rustup target add x86_64-unknown-linux-musl
      shell: bash
    - run: sudo apt-get install build-essential cmake pkg-config libssl-dev git llvm clang libclang-dev protobuf-compiler musl-tools
      shell: bash

