#!/usr/bin/env bash
GRAMINE_DIR="$PWD/cruntime"
PAL_CMD="$GRAMINE_DIR/sgx/loader"
LIBPAL_PATH="$GRAMINE_DIR/sgx/libpal.so"

APPLICATION=


while [ "$1" != "" ];
do
	if [ "$APPLICATION" == "" ]; then
		APPLICATION=$1
		shift
		continue
	fi
	break
done

if [ "$APPLICATION" == "" ]; then
	echo "Usage: $0 [<application>] <args>..."
	exit 2
fi

if [ ! -e "$APPLICATION.manifest.sgx" ]; then
    echo "Invalid application path specified ($APPLICATION.manifest.sgx does not exist)." >&2
    echo "The path should point to application configuration files, so that they can be" >&2
    echo "found after appending corresponding extensions." >&2
    exit 2
fi

if [ ! -f "$PAL_CMD" ]; then
	echo "$PAL_CMD not found"
	exit 1
fi

"$PAL_CMD" "$LIBPAL_PATH" init "$APPLICATION" "$@"
echo "$APPLICATION exited with code $?"
