[package]
name = "transaction-builder"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem transaction-builder"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
edition = "2018"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.3", optional = true }

transaction-builder-generated = { path = "../../client/transaction-builder", version = "0.1.0" }

[features]
#default = []
default = ["std", "mesalock_sgx"]
std = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
