os:
  - linux
  - osx
    # Windows is troublesome and useless
    #  - windows
dist: bionic
sudo: false

language: rust
rust:
  - stable
  - nightly

stages:
  - name: test
  - name: lint

install: true

# Default script is the "test" stage
script:
  - cargo build
  - cargo test
  - examples/build_examples.sh

jobs:
  include:
    - stage: lint
      if: os = linux
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

cache: cargo
