image: rustlang/rust:nightly

pipelines:
    branches:
        '*':
            - step:
                caches:
                    - cargo
                    - rust-target
                script:
                    - echo "Build project"                    ; cargo build --release
                    - echo "Run unit tests"                   ; cargo test --lib --release -v --no-fail-fast -- --nocapture --test
                    - echo "Run documentation tests"          ; cargo test --doc --release -v --no-fail-fast -- --nocapture --test
definitions:
  caches:
    cargo: /usr/local/cargo # CARGO_HOME
    rust-target: $BITBUCKET_CLONE_DIR/target

