[package]
authors = ['Phala Network']
edition = '2018'
name = 'pallet-claim'
version = "2.0.0"
license = "Apache 2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/Phala-Network/phala-blockchain"
description = "FRAME pallet template"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.102", default-features = false }
serde_derive = { version = "1.0.102", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
rustc-hex = { version = "2.0.1", default-features = false }
frame-support = { version = "2.0.0", default-features = false, path = "../../substrate/frame/support" }
frame-system = { version = "2.0.0", default-features = false, path = "../../substrate/frame/system" }
sp-std = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/std" }
sp-io = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/io" }

[dependencies.pallet-balances]
default-features = false
version = "2.0.0"
path = "../../substrate/frame/balances"

[dev-dependencies]
sp-core = { default-features = false, version = '2.0.0' }
sp-io = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/io" }
sp-runtime = { default-features = false, version = '2.0.0' }


[features]
default = ['std']
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
]
