[package]
name = "diem-workspace-hack"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem workspace hack"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.3", optional = true }
byteorder = { git = "https://github.com/mesalock-linux/byteorder-sgx.git", features = ["i128", "std"] }
bytes = { git = "https://github.com/mesalock-linux/bytes-sgx.git", features = ["serde", "std"] }
# cc = { version = "1.0.66", features = ["jobserver", "parallel"] }
chrono = { git = "https://github.com/mesalock-linux/chrono-sgx.git" }
itertools = { git = "https://github.com/mesalock-linux/rust-itertools-sgx.git" }
itoa = { git = "https://github.com/mesalock-linux/itoa-sgx.git" }
log = { git = "https://github.com/mesalock-linux/log-sgx.git", features = ["serde", "std"] }
memchr = { git = "https://github.com/mesalock-linux/rust-memchr-sgx.git", features = ["use_std"] }
num-integer = { git = "https://github.com/mesalock-linux/num-integer-sgx.git", features = ["i128", "std"] }
num-traits = { git = "https://github.com/mesalock-linux/num-traits-sgx.git", features = ["i128", "std"] }
once_cell = { git = "https://github.com/mesalock-linux/once_cell-sgx.git" }
# petgraph = { version = "0.5.1", features = ["graphmap", "matrix_graph", "stable_graph"] }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git", features = ["derive", "rc"] }
sha-1 = { git = "https://github.com/mesalock-linux/rust-sha1-sgx.git", package = "sha1", features = ["std"] }
subtle = { git = "https://github.com/mesalock-linux/subtle-sgx.git", features = ["i128", "std"] }

[build-dependencies]
syn = { version = "1.0.58", features = ["clone-impls", "derive", "extra-traits", "fold", "full", "parsing", "printing", "proc-macro", "quote", "visit", "visit-mut"] }

[features]
default = ["std", "mesalock_sgx"]
std = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
