[workspace]

[package]
edition = "2021"
name = "sideprog"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.16"
once_cell = "1.10.0"
pink-sidevm = {version = "0.1", path = "../../../sidevm/sidevm"}
tokio = {version = "1", features = ["macros"]}
futures = "0.3"
