[package]
name = "diem-crypto"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diem-crypto"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.3", optional = true }
anyhow = { git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
bytes = { git = "https://github.com/mesalock-linux/bytes-sgx.git" }
# vanilla-curve25519-dalek = { version = "3", package = 'curve25519-dalek', default-features = false, features = ["std"], optional = true }
# curve25519-dalek = { git = "https://github.com/novifinancial/curve25519-dalek.git", branch = "fiat3", version = "3", default-features = false, features = ["std", "fiat_u64_backend"], optional = true }
curve25519-dalek = { path = "../../vendor/curve25519-dalek", version = "3", package = 'curve25519-dalek', optional = true }
digest = { path = "../../vendor/digest" }
# vanilla-ed25519-dalek = { version = "1.0.1", package = 'ed25519-dalek', default-features = false, features = ["std"], optional = true }
# ed25519-dalek = { git = "https://github.com/novifinancial/ed25519-dalek.git", branch = "fiat5", version = "1.0.1", default-features = false, features = ["std", "fiat_u64_backend", "serde"], optional = true }
ed25519-dalek = { path = "../../vendor/ed25519-dalek", package = 'ed25519-dalek', default-features = false, features = ["std"], optional = true }
hex = { git = "https://github.com/mesalock-linux/rust-hex-sgx.git" }
hkdf = { path = "../../vendor/hkdf", version = "0.10.0" }
once_cell = { git = "https://github.com/mesalock-linux/once_cell-sgx.git" }
# mirai-annotations = "1.10.1"
# proptest = { version = "0.10.1", optional = true }
# proptest-derive = { version = "0.2.0", optional = true }
rand = { git = "https://github.com/mesalock-linux/rand-sgx.git", tag = "v0.7.3_sgx1.1.3" }
rand_core = { git = "https://github.com/mesalock-linux/rand-sgx.git", tag = "v0.7.3_sgx1.1.3", default-features = false }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git", features = ["derive"] }
serde_bytes = { path = "../../vendor/serde_bytes" }
serde-name = { path = "../../vendor/serde-name", version = "0.1.1" }
sha2 = { path = "../../vendor/sha2", version = "0.9.2" }
short-hex-str = { path = "../../common/short-hex-str", version = "0.1.0" }
static_assertions = "1.1.0"
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
# vanilla-x25519-dalek = { version = "1.1.0", package = 'x25519-dalek', default-features = false, features = ["std"], optional = true }
# x25519-dalek = { git = "https://github.com/novifinancial/x25519-dalek.git", branch = "fiat4", version = "1.1.0", default-features = false, features = ["std", "fiat_u64_backend"], optional = true}
x25519-dalek = { path = "../../vendor/x25519-dalek", version = "1.1.0", package = 'x25519-dalek', default-features = false, features = ["std"], optional = true }
aes-gcm = { path = "../../vendor/aes-gcm", version = "0.8.0" }
diem-crypto-derive = { path = "../crypto-derive", version = "0.1.0" }
bcs = { path = "../../vendor/bcs" }
diem-nibble = { path = "../../common/nibble", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }

[dev-dependencies]
bitvec = "0.19.4"
byteorder = "1.4.2"
proptest = "0.10.1"
proptest-derive = "0.2.0"
ripemd160 = "0.9.1"
criterion = "0.3.3"
sha3 = "0.9.1"
serde_json = { git = "https://github.com/mesalock-linux/serde-json-sgx.git" }
trybuild = "1.0.38"

[features]
default = ["std", "mesalock_sgx", "u64"]
std = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
assert-private-keys-not-cloneable = []
cloneable-private-keys = []
u64 = ["curve25519-dalek/u64_backend", "ed25519-dalek/u64_backend", "x25519-dalek/u64_backend"]
u32 = ["curve25519-dalek/u32_backend", "ed25519-dalek/u32_backend", "x25519-dalek/u32_backend"]
# fuzzing = ["proptest", "proptest-derive", "cloneable-private-keys"]
# fiat = ["curve25519-dalek", "ed25519-dalek", "x25519-dalek"]
# vanilla-u64 = ["vanilla-curve25519-dalek/u64_backend", "vanilla-ed25519-dalek/u64_backend", "vanilla-x25519-dalek/u64_backend"]
# vanilla-u32 = ["vanilla-curve25519-dalek/u32_backend", "vanilla-ed25519-dalek/u32_backend", "vanilla-x25519-dalek/u32_backend"]

[[bench]]
name = "noise"
harness = false

[[bench]]
name = "ed25519"
harness = false
