[package]
name = "diem-nibble"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diem-nibble"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.3", optional = true }
diem-workspace-hack = { path = "../workspace-hack", version = "0.1.0" } # Useless
# proptest = { version = "0.10.1", optional = true } # TODO: Doesn't support SGX
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git", features = ["derive"] }

[features]
default = ["std", "mesalock_sgx"]
std = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
fuzzing = [] # ["proptest"]
