[package]
name = "move-core-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Core types for Move"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.3", optional = true }
anyhow = { git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
hex = { git = "https://github.com/mesalock-linux/rust-hex-sgx.git" }
rand = { git = "https://github.com/mesalock-linux/rand-sgx.git", tag = "v0.7.3_sgx1.1.3" }
# proptest = { version = "0.10.1", default-features = false, optional = true }
# mirai-annotations = "1.10.1"
# proptest-derive = { version = "0.2.0", default-features = false, optional = true }
ref-cast = "1.0.6"
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git" } # , default-features = false
serde_bytes = { path = "../../../vendor/serde_bytes" }
static_assertions = "1.1.0"
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }
once_cell = { git = "https://github.com/mesalock-linux/once_cell-sgx.git" }

bcs = { path = "../../../vendor/bcs", version = "0.1.2" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
diem-crypto = { path = "../../../crypto/crypto", version = "0.1.0", default-features = false }
diem-crypto-derive = { path = "../../../crypto/crypto-derive", version = "0.1.0" }
short-hex-str = { path = "../../../common/short-hex-str", version = "0.1.0" }

[dev-dependencies]
once_cell = { git = "https://github.com/mesalock-linux/once_cell-sgx.git" }
proptest = "0.10.1"
proptest-derive = "0.2.0"
regex = "1.4.3"
serde_json = "1.0.61"

[features]
default = ["std", "mesalock_sgx", "u64"]
std = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
u64 = ["diem-crypto/u64"]
fuzzing = []
# fiat = ["diem-crypto/fiat"]
# vanilla = ["diem-crypto/vanilla-u64"]
# fuzzing = ["proptest", "proptest-derive"]
