[package]
name = "diem-network-address"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem types"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.3", optional = true }
aes-gcm = { path = "../../vendor/aes-gcm", version = "0.8.0" }
# proptest = { version = "0.10.1", optional = true }
# proptest-derive = { version = "0.2.0", optional = true }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git", default-features = false }
serde_bytes = { path = "../../vendor/serde_bytes" }
static_assertions = "1.1.0"
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }

bcs = { path = "../../vendor/bcs", version = "0.1.2" }
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
move-core-types = { path = "../../language/move-core/types", version = "0.1.0" }

[dev-dependencies]
anyhow = "1.0.38"
proptest = "0.10.1"
proptest-derive = "0.2.0"

diem-crypto = { path = "../../crypto/crypto", version = "0.1.0", features = ["fuzzing"] }

[features]
default = ["std", "mesalock_sgx"]
std = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
fuzzing = [] # ["proptest", "proptest-derive", "diem-crypto/fuzzing"]
